# Publishes veloren-server-cli to the gitlab container registry
# https://gitlab.com/veloren/veloren/container_registry
.check:
  stage: check
  tags:
    - veloren-docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - when: always

build-pages:
  extends: .check
  script:
    - cargo install --git https://github.com/getzola/zola.git --rev  84ecd2ac5e2913426ea6e6a9dc55928e81d0df25;
    - zola build