# Publishes veloren-server-cli to the gitlab container registry
# https://gitlab.com/veloren/veloren/container_registry
.publish:
  stage: publish
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: never

pages:
  extends: .publish
  image: ubuntu
  artifacts:
    paths:
      - public
  script:
    - apt update && apt install wget -y
    - wget -c https://github.com/getzola/zola/releases/download/v0.16.0/zola-v0.16.0-x86_64-unknown-linux-gnu.tar.gz -O - | tar -xz
    - ./zola build